### PR TITLE
Add `CleanWebpackPlugin` to webpack config, so the `build` directory is cleared

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Added `CleanWebpackPlugin` to webpack config, so the `build` directory is cleared after each build. Part of ckeditor/ckeditor5#700.

### CODE REVIEW

**Comment by Reinmar** [comment]
I'm sorry but I don't like it. I don't want another dependency, especially not in a 0.x version (although, yea... it has 500k downloads monthly :D). 

Anyway, I don't see a problem in clearing stuff at the beginning of the build script.

**Comment by ma2ciek** [comment]
I think that both approaches have some downsides. We've discussed them here: ckeditor/ckeditor5#700.

**Comment by Reinmar** [comment]
I replied in https://github.com/ckeditor/ckeditor5/issues/700#issuecomment-348450847.

**Comment by ma2ciek** [comment]
It's not valid. See https://github.com/ckeditor/ckeditor5/issues/700#issuecomment-348450847

**Pull request closed without merging**
