### PR TITLE
T/10: Getting rid of config-editor.js

### LINKED ISSUE #10: Getting rid of config-editor.js
Couldn't we just have an entry named `config` in `config-build.js` with the configurations of the built editor? 

This would allow one to be focused in one file only. Also, a common task will be adding features, having two files to remember to touch just makes it more painful. Or when I remove one plugin, I forget to remove it from the other file.

In few words, it would just make it simpler.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Removed two configuration files. Editor configuration was moved to the `config-build.js` Closes #10.

### CODE REVIEW

**Comment by pomek** [comment]
Requires https://github.com/ckeditor/ckeditor5-dev/pull/218.

**Comment by pomek** [comment]
I will add compat build because I forgot to add it.

**Comment by pomek** [comment]
Ok, ready.

**Comment by Reinmar** [comment]
First of all, the name of the file was supposed to change. Second, see my [last comment](https://github.com/ckeditor/ckeditor5-build-classic/issues/10#issuecomment-303399825) – it'd be better to copy the content of the config.

**Comment by pomek** [comment]
Fixed.

**Pull request merged**
